version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./app/dist/:/var/www/
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
     - NGINX_PORT=80
    ports:
      - "80:80"
  app:
    env_file: .env
    build:
      context: .
      dockerfile: ./config/Dockerfile
      args:
        APP_NAME: ${APP_NAME}
    command: npm run build
    environment:
      NODE_PATH: ${NODE_PATH}
    volumes:
      - ./app/src:/usr/${APP_NAME}/src
      - ./app/dist:/usr/${APP_NAME}/dist
    ports:
      - "8080:8080"