version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./app/dist/:/var/www/
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    env_file: ./.env
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
  api:
    build:
      context: .
      dockerfile: ./config/api/Dockerfile
    command: npm start
    env_file: ./.env
    volumes:
      - ./api/src:/usr/api/src
    ports:
      - "${API_PORT}:3000"
  app:
    env_file: .env
    build:
      context: .
      dockerfile: ./config/app/Dockerfile
      args:
        APP_NAME: ${APP_NAME}
    command: npm run build
    env_file: ./.env
    volumes:
      - ./app/src:/usr/${APP_NAME}/src
      - ./app/dist:/usr/${APP_NAME}/dist
    ports:
      - "8080:8080"
